project_id = "thhbrznetqliogjxruml"

[functions.paystack]
verify_jwt = false

[functions.kvdata]
verify_jwt = false

[functions.reconciliation-cron]
verify_jwt = false

[functions.notification-engine]
verify_jwt = false
